[project]
name = 'SyncsHC'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sysnc]
path = 'contracts/sysnc.clar'
clarity_version = 4
epoch = 'latest'

[contracts.piggy-bank]
path = 'contracts/piggy-bank.clar'
clarity_version = 4
epoch = 'latest'

[contracts.piggy-bank-factory]
path = 'contracts/piggy-bank-factory.clar'
clarity_version = 4
epoch = 'latest'

[contracts.token-manager]
path = 'contracts/token-manager.clar'
clarity_version = 4
epoch = 'latest'

[contracts.piggy-bank-registry]
path = 'contracts/piggy-bank-registry.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
